default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: smate_development
  # username: smate
  # password: peeshuBooL5haed

test:
  <<: *default
  database: smate_test

production:
  <<: *default
  database: smate_production
  username: smate
  password: <%= ENV['SMATE_DATABASE_PASSWORD'] %>
